### ISSUE TITLE
what are ALL of the mods this is compatible with?

### ISSUE THREAD

**Issue by pat600130** [jonko0493/ComputerCartographer#6]
and could you say it DIRECTLY on the wiki or something, so like as an example it could say "As of now this mod is compatible with . . ."

**Comment by jonko0493** [comment]
You don't list the mods a mod is compatible with. It is assumed compatible with all mods unless otherwise listed, because I'm not going to test every mod out there. Afaik, there are no incompatibilities with this mod and others.
